
spring:
  datasource:
    url: jdbc:mysql://localhost:8889/gymportal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: gymportal
    password: gymportal
    driver-class-name: com.mysql.cj.jdbc.Driver
  

###############################################
########### GYMPORTAL PROPERTIES ###############
###############################################

