server:
  servlet:
    context-path: /myunivaq

spring:
  application:
    name: MyUnivaq
  profiles:
    active: dev
  #jackson:
    #default-property-inclusion: NON_NULL
    #serialization:
      #write-dates-as-timestamps: true
  messages:
    basename: i18n/common, i18n/myunivaq
    encoding: UTF-8
    use-code-as-default-message: true
    
###############################################
############# MYUNIVAQ PROPERTIES #############
###############################################

myunivaq:
  dateformat: dd/MM/yyyy