
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myunivaq?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: myunivaq
    password: myunivaq
    driver-class-name: com.mysql.cj.jdbc.Driver
  

###############################################
########### MYUNIVAQ PROPERTIES ###############
###############################################

